[[bin]]
name = "polkadot"
path = "src/main.rs"

[package]
name = "polkadot"
description = "Implementation of a https://polkadot.network node in Rust based on the Substrate framework."
license = "GPL-3.0-only"
version = "0.9.5"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
readme = "README.md"

[dependencies]
polkadot-cli = { path = "cli", features = [ "kusama-native", "westend-native", "rococo-native" ]  }
color-eyre = { version = "0.5.11", default-features = false }
parity-util-mem = { version = "*", default-features = false, features = ["jemalloc-global"] }

[dev-dependencies]
assert_cmd = "1.0.2"
nix = "0.19.1"
tempfile = "3.2.0"

[workspace]
members = [
	"cli",
	"core-primitives",
	"erasure-coding",
	"primitives",
	"runtime/common",
	"runtime/common/slot_range_helper",
	"runtime/parachains",
	"runtime/polkadot",
	"runtime/kusama",
	"runtime/rococo",
	"runtime/westend",
	"runtime/test-runtime",
	"statement-table",
	"xcm",
	"xcm/xcm-builder",
	"xcm/xcm-executor",
	"xcm/pallet-xcm",
	"node/client",
	"node/collation-generation",
	"node/core/approval-voting",
	"node/core/av-store",
	"node/core/backing",
	"node/core/bitfield-signing",
	"node/core/candidate-validation",
	"node/core/chain-api",
	"node/core/dispute-coordinator",
	"node/core/dispute-participation",
	"node/core/parachains-inherent",
	"node/core/provisioner",
	"node/core/pvf",
	"node/core/runtime-api",
	"node/network/approval-distribution",
	"node/network/bridge",
	"node/network/protocol",
	"node/network/statement-distribution",
	"node/network/bitfield-distribution",
	"node/network/availability-distribution",
	"node/network/availability-recovery",
	"node/network/collator-protocol",
	"node/network/gossip-support",
	"node/overseer",
	"node/primitives",
	"node/service",
	"node/subsystem",
	"node/subsystem/dispatch-gen",
	"node/subsystem-test-helpers",
	"node/subsystem-util",
	"node/jaeger",
	"node/metered-channel",
	"node/test/client",
	"node/test/service",
	"parachain/test-parachains",
	"parachain/test-parachains/adder",
	"parachain/test-parachains/adder/collator",
]

# We want to be able to build the bridge relayer without pulling it (and all of its
# dependencies into the Polkadot workspace)
exclude = ["bridges/relays/bin-substrate", "bridges/bin/rialto/runtime", "bridges/bin/millau/runtime"]

[badges]
maintenance = { status = "actively-developed" }

# make sure dev builds with backtrace do
# not slow us down
[profile.dev.package.backtrace]
opt-level = 3

[profile.release]
# Polkadot runtime requires unwinding.
panic = "unwind"

[features]
runtime-benchmarks= [ "polkadot-cli/runtime-benchmarks" ]
try-runtime = [ "polkadot-cli/try-runtime" ]

# Configuration for building a .deb package - for use with `cargo-deb`
[package.metadata.deb]
name = "polkadot"
extended-description = "Implementation of a https://polkadot.network node in Rust based on the Substrate framework."
section = "misc"
maintainer = "martin@parity.io"
license-file = ["LICENSE", "0"]
# https://www.debian.org/doc/debian-policy/ch-maintainerscripts.html
maintainer-scripts = "scripts/packaging/deb-maintainer-scripts"
assets = [
	["target/release/polkadot", "/usr/bin/", "755"],
	["scripts/packaging/polkadot.service", "/lib/systemd/system/", "644"]
]
conf-files = [
	"/etc/default/polkadot"
]

# Configuration for building an .rpm package - for use with `cargo-rpm`
[package.metadata.rpm]
package = "polkadot"

[package.metadata.rpm.cargo]
buildflags = ["--release"]

[package.metadata.rpm.targets]
polkadot = { path = "/usr/bin/polkadot" }

[package.metadata.rpm.files]
"../scripts/packaging/polkadot.service" = { path = "/usr/lib/systemd/system/polkadot.service", mode = "644" }


[patch.'https://github.com/paritytech/substrate']
sp-core = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sc-client-api = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
pallet-treasury = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
pallet-randomness-collective-flip = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
pallet-babe = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sp-trie = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sp-keyring = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
pallet-timestamp = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
frame-system = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
frame-try-runtime = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
frame-system-benchmarking = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
pallet-staking = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
frame-support = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
pallet-session = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
pallet-balances = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
pallet-authorship = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sp-staking = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sp-runtime = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sp-io = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sp-std = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sp-inherents = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sp-api = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
pallet-sudo = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
frame-system-rpc-runtime-api = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
pallet-staking-reward-curve = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
pallet-offences = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
pallet-nicks = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
pallet-membership = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
pallet-indices = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
pallet-im-online = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
pallet-identity = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
pallet-grandpa = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
frame-executive = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
pallet-elections-phragmen = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
pallet-election-provider-multi-phase = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
frame-election-provider-support = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
frame-metadata = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
frame-support-test = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
remote-externalities = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sc-informant = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sc-finality-grandpa-warp-sync = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sp-database = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
substrate-browser-utils = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
try-runtime-cli = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
pallet-democracy = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
pallet-collective = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
pallet-transaction-payment-rpc = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
pallet-transaction-payment-rpc-runtime-api = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
pallet-transaction-payment = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
pallet-authority-discovery = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sp-transaction-pool = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sp-version = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sp-session = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sp-offchain = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sp-consensus-babe = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
pallet-recovery = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
pallet-society = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
fork-tree = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
pallet-utility = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sc-network = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sc-cli = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sc-client-db = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sc-executor = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sc-service = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sc-keystore = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sp-authority-discovery = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sp-block-builder = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sp-blockchain = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sc-network-gossip = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sp-state-machine = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sp-externalities = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sp-runtime-interface = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sp-application-crypto = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sp-serializer = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sc-rpc = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
substrate-frame-rpc-system = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sc-authority-discovery = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sc-chain-spec = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sc-finality-grandpa = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sc-telemetry = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sc-transaction-pool = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sp-timestamp = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sc-block-builder = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sp-finality-grandpa = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sp-tracing = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
substrate-prometheus-endpoint = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sp-keystore = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
frame-benchmarking = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
frame-benchmarking-cli = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
pallet-bounties = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
pallet-multisig = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
pallet-scheduler = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
pallet-tips = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
pallet-proxy = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
pallet-vesting = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sc-basic-authorship = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sp-consensus = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sp-consensus-slots = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sc-consensus = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sc-consensus-babe = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sc-consensus-babe-rpc = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sc-consensus-epochs = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sc-consensus-slots = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sp-consensus-vrf = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sp-consensus-aura = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sp-wasm-interface = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sc-finality-grandpa-rpc = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sc-light = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sc-sync-state-rpc = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sp-arithmetic = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sp-storage = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sc-tracing = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sp-test-primitives = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
substrate-build-script-utils = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
substrate-test-client = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
substrate-test-runtime = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
substrate-test-runtime-client = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
substrate-test-utils = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
substrate-wasm-builder = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sp-npos-elections = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sp-npos-elections-compact = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
pallet-offences-benchmarking = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
pallet-session-benchmarking = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
pallet-gilt = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
pallet-mmr = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
pallet-mmr-primitives = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
pallet-mmr-rpc = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sp-rpc = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
pallet-staking-reward-fn = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sp-maybe-compressed-blob = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sc-executor-common = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sc-executor-wasmtime = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sc-consensus-uncles = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sp-authorship = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
sp-utils = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
max-encoded-len = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
max-encoded-len-derive = { git="https://github.com/cheme/substrate", branch="paged_child_keys" }
