[[bin]]
name = "polkadot"
path = "src/main.rs"

[package]
name = "polkadot"
version = "0.8.23"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
cli = { package = "polkadot-cli", path = "cli" }
futures = "0.3.4"
service = { package = "polkadot-service", path = "service" }
parity-util-mem = { version = "*", default-features = false, features = ["jemalloc-global"] }

[dev-dependencies]
assert_cmd = "0.12"
nix = "0.17"
tempfile = "3.1.0"

[workspace]
members = [
	"cli",
	"core-primitives",
	"erasure-coding",
	"primitives",
	"runtime/common",
	"runtime/parachains",
	"runtime/polkadot",
	"runtime/kusama",
	"runtime/rococo-v1",
	"runtime/westend",
	"runtime/test-runtime",
	"runtime/test-runtime/client",
	"service",
	"statement-table",
	"service",
	"validation",

	"node/collation-generation",
	"node/core/av-store",
	"node/core/backing",
	"node/core/bitfield-signing",
	"node/core/candidate-validation",
	"node/core/chain-api",
	"node/core/proposer",
	"node/core/provisioner",
	"node/core/runtime-api",
	"node/network/bridge",
	"node/network/pov-distribution",
	"node/network/protocol",
	"node/network/statement-distribution",
	"node/network/bitfield-distribution",
	"node/network/availability-distribution",
	"node/overseer",
	"node/primitives",
	"node/service",
	"node/subsystem",
	"node/subsystem-test-helpers",
	"node/subsystem-util",
	"node/test-service",

	"parachain/test-parachains",
	"parachain/test-parachains/adder",
]

[badges]
maintenance = { status = "actively-developed" }

[profile.release]
# Polkadot runtime requires unwinding.
panic = "unwind"

[features]
runtime-benchmarks=["cli/runtime-benchmarks"]
service-rewr= [
	"cli/service-rewr",
]

[patch.'https://github.com/paritytech/substrate']
sp-core = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sc-client-api = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
pallet-vesting = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
pallet-treasury = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
pallet-randomness-collective-flip = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
pallet-babe = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sp-trie = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sp-keyring = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
pallet-timestamp = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
frame-system = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
pallet-staking = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
frame-support = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
pallet-session = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
pallet-balances = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
pallet-authorship = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sp-staking = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sp-runtime = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sp-io = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sp-std = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sp-inherents = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sp-api = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
pallet-sudo = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
frame-system-rpc-runtime-api = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
pallet-staking-reward-curve = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
pallet-offences = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
pallet-nicks = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
pallet-membership = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
pallet-indices = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
pallet-im-online = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
pallet-identity = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
pallet-grandpa = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
pallet-finality-tracker = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
frame-executive = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
pallet-elections-phragmen = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
pallet-democracy = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
pallet-collective = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
pallet-transaction-payment-rpc = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
pallet-transaction-payment-rpc-runtime-api = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
pallet-transaction-payment = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
pallet-authority-discovery = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sp-transaction-pool = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sp-version = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sp-session = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sp-offchain = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sp-consensus-babe = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
pallet-recovery = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
pallet-society = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
substrate-browser-utils = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
fork-tree = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
pallet-utility = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sc-network = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sc-cli = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sc-client-db = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sc-executor = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sc-service = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sc-keystore = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sp-authority-discovery = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sp-block-builder = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sp-blockchain = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sp-consensus = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sc-network-gossip = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sp-state-machine = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sp-externalities = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sp-runtime-interface = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sp-application-crypto = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sp-serializer = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sc-rpc = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
substrate-frame-rpc-system = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sc-authority-discovery = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sc-chain-spec = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sc-consensus-babe = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sc-finality-grandpa = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sc-telemetry = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sc-transaction-pool = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sp-timestamp = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sc-block-builder = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sp-finality-grandpa = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sp-wasm-interface = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
substrate-prometheus-endpoint = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
substrate-test-client = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
substrate-test-runtime = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
substrate-test-runtime-client = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
substrate-wasm-builder-runner = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sp-consensus-aura = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sc-network-test = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
frame-benchmarking = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
frame-benchmarking-cli = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
frame-system-benchmarking = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
pallet-multisig = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
pallet-offences-benchmarking = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
pallet-proxy = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
pallet-scheduler = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
pallet-session-benchmarking = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sc-consensus = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sc-consensus-epochs = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sc-light = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sc-basic-authorship = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sc-consensus-babe-rpc = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sc-rpc-api = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sc-finality-grandpa-rpc = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sc-proposer-metrics = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sp-chain-spec = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sp-rpc = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
substrate-build-script-utils = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sp-arithmetic = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }
sp-storage = { git="https://github.com/cheme/substrate", branch="light_grandpa_warp" }


