[[bin]]
name = "polkadot"
path = "src/main.rs"

[package]
name = "polkadot"
version = "0.7.19"
authors = ["Parity Technologies <admin@parity.io>"]
build = "build.rs"
edition = "2018"

[dependencies]
cli = { package = "polkadot-cli", path = "cli" }
futures = "0.3.1"
ctrlc = { version = "3.1.3", features = ["termination"] }
service = { package = "polkadot-service", path = "service" }

[build-dependencies]
vergen = "3.0.4"

[workspace]
members = [
	"availability-store",
	"cli",
	"collator",
	"erasure-coding",
	"network",
	"primitives",
	"runtime/common",
	"runtime/polkadot",
	"runtime/kusama",
	"service",
	"statement-table",
	"service",
	"validation",

	"test-parachains/adder",
	"test-parachains/adder/collator",
]
exclude = [
	"runtime/polkadot/wasm",
	"runtime/kusama/wasm",
	"test-parachains/adder/wasm",
]

[badges]
maintenance = { status = "actively-developed" }

[profile.release]
# Polkadot runtime requires unwinding.
panic = "unwind"

[patch.'https://github.com/paritytech/substrate']
sp-core = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
sc-client = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
sc-client-api = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
pallet-treasury = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
pallet-randomness-collective-flip = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
pallet-babe = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
sp-trie = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
sp-keyring = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
pallet-timestamp = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
frame-system = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
pallet-staking = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
frame-support = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
pallet-session = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
pallet-balances = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
pallet-authorship = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
sp-staking = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
sp-runtime = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
sp-io = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
sp-std = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
sp-inherents = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
sp-api = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
pallet-sudo = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
frame-system-rpc-runtime-api = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
pallet-staking-reward-curve = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
pallet-offences = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
pallet-nicks = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
pallet-membership = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
pallet-indices = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
pallet-im-online = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
pallet-identity = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
pallet-grandpa = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
pallet-finality-tracker = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
frame-executive = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
pallet-elections-phragmen = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
pallet-democracy = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
pallet-collective = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
pallet-transaction-payment-rpc = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
pallet-transaction-payment-rpc-runtime-api = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }

pallet-transaction-payment = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
pallet-authority-discovery = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
sp-transaction-pool = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
sp-version = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
sp-session = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
sp-offchain = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
sp-consensus-babe = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
pallet-recovery = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
pallet-society = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
browser-utils = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
fork-tree = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
pallet-utility = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
grafana-data-source = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
sc-network = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
sc-cli = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
sc-client-db = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
sc-executor = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
sc-service = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
sc-keystore = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
sp-authority-discovery = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
sp-block-builder = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
sp-blockchain = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
sp-consensus = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
sc-network-gossip = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
sp-state-machine = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
sp-externalities = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
sp-runtime-interface = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
sp-application-crypto = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
sp-serializer = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
sc-rpc = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
substrate-frame-rpc-system = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
sc-authority-discovery = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
sc-chain-spec = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
sc-consensus-babe = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
sc-finality-grandpa = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
sc-telemetry = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
sc-transaction-pool = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
sp-timestamp = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
sc-block-builder = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }
sp-finality-grandpa = { git="https://github.com/cheme/substrate", branch="polka_overlay_change" }

