[[bin]]
name = "polkadot"
path = "src/main.rs"

[package]
name = "polkadot"
version = "0.8.10"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
cli = { package = "polkadot-cli", path = "cli" }
# It looks like this is the only way to pass features to it
collator = { package = "polkadot-collator", path = "collator" }
futures = "0.3.4"
service = { package = "polkadot-service", path = "service" }
parity-util-mem = { version = "*", default-features = false, features = ["jemalloc-global"] }

[dev-dependencies]
assert_cmd = "0.12"
nix = "0.17"
tempfile = "3.1.0"

[workspace]
members = [
	"availability-store",
	"cli",
	"collator",
	"erasure-coding",
	"network",
	"network/test",
	"primitives",
	"runtime/common",
	"runtime/parachains",
	"runtime/polkadot",
	"runtime/kusama",
	"runtime/westend",
	"runtime/test-runtime",
	"runtime/test-runtime/client",
	"service",
	"statement-table",
	"service",
	"validation",

	"node/messages",
	"node/overseer",
	"node/primitives",
	"node/service",

	"parachain/test-parachains",
	"parachain/test-parachains/adder",
	"parachain/test-parachains/adder/collator",
	"parachain/test-parachains/code-upgrader",
]
exclude = [
	"runtime/polkadot/wasm",
	"runtime/kusama/wasm",
	"runtime/westend/wasm",
	"parachain/test-parachains/adder/wasm",
]

[badges]
maintenance = { status = "actively-developed" }

[profile.release]
# Polkadot runtime requires unwinding.
panic = "unwind"

[features]
runtime-benchmarks=["cli/runtime-benchmarks"]

service-rewr= [
	"cli/service-rewr",
	"collator/service-rewr",
]

[patch.'https://github.com/paritytech/substrate']
sp-core = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
sc-client-api = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
pallet-vesting = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
pallet-treasury = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
pallet-randomness-collective-flip = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
pallet-babe = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
sp-trie = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
sp-keyring = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
pallet-timestamp = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
frame-system = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
pallet-staking = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
frame-support = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
pallet-session = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
pallet-balances = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
pallet-authorship = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
sp-staking = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
sp-runtime = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
sp-io = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
sp-std = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
sp-inherents = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
sp-api = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
pallet-sudo = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
frame-system-rpc-runtime-api = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
pallet-staking-reward-curve = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
pallet-offences = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
pallet-nicks = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
pallet-membership = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
pallet-indices = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
pallet-im-online = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
pallet-identity = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
pallet-grandpa = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
pallet-finality-tracker = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
frame-executive = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
pallet-elections-phragmen = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
pallet-democracy = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
pallet-collective = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
pallet-transaction-payment-rpc = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
pallet-transaction-payment-rpc-runtime-api = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
pallet-transaction-payment = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
pallet-authority-discovery = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
sp-transaction-pool = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
sp-version = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
sp-session = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
sp-offchain = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
sp-consensus-babe = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
pallet-recovery = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
pallet-society = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
substrate-browser-utils = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
fork-tree = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
pallet-utility = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
sc-network = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
sc-cli = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
sc-client-db = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
sc-executor = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
sc-service = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
sc-keystore = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
sp-authority-discovery = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
sp-block-builder = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
sp-blockchain = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
sp-consensus = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
sc-network-gossip = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
sp-state-machine = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
sp-externalities = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
sp-runtime-interface = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
sp-application-crypto = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
sp-serializer = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
sc-rpc = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
substrate-frame-rpc-system = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
sc-authority-discovery = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
sc-chain-spec = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
sc-consensus-babe = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
sc-finality-grandpa = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
sc-telemetry = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
sc-transaction-pool = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
sp-timestamp = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
sc-block-builder = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
sp-finality-grandpa = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
sp-wasm-interface = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
substrate-prometheus-endpoint = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
substrate-test-client = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
substrate-test-runtime = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
substrate-test-runtime-client = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
substrate-wasm-builder-runner = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
sp-consensus-aura = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
sc-network-test = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
frame-benchmarking = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
frame-benchmarking-cli = { git="https://github.com/cheme/substrate", branch="historied-storage-cache" }
