[package]
name = "polkadot-rpc"
version = "0.6.17"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
client = { package = "substrate-client", git = "https://github.com/cheme/substrate", branch = "overlay_change" }
jsonrpc-core = "14.0.3"
polkadot-primitives = { path = "../primitives" }
sr-primitives = { git = "https://github.com/cheme/substrate", branch = "overlay_change"  }
substrate-rpc = { git = "https://github.com/cheme/substrate", branch = "overlay_change" }
transaction_pool = { package = "substrate-transaction-pool", git = "https://github.com/cheme/substrate", branch = "overlay_change"  }
paint-system-rpc = { git = "https://github.com/cheme/substrate", branch = "overlay_change"  }
paint-transaction-payment-rpc = { git = "https://github.com/cheme/substrate", branch = "overlay_change" }
polkadot-runtime = { path = "../runtime" }

