[package]
name = "polkadot-service"
version = "0.6.17"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
parking_lot = "0.9.0"
lazy_static = "1.4.0"
log = "0.4.8"
futures = "0.1.29"
exit-future = "0.1.4"
slog = "2.5.2"
hex-literal = "0.2.1"
av_store = { package = "polkadot-availability-store", path = "../availability-store" }
consensus = { package = "polkadot-validation", path = "../validation" }
polkadot-primitives = { path = "../primitives" }
polkadot-runtime = { path = "../runtime" }
polkadot-executor = { path = "../executor" }
polkadot-network = { path = "../network"  }
polkadot-rpc = { path = "../rpc" }
sr-io = { git = "https://github.com/cheme/substrate", branch = "child_uuid_nt" }
sr-api = { git = "https://github.com/cheme/substrate", branch = "child_uuid_nt" }
sr-primitives = { git = "https://github.com/cheme/substrate", branch = "child_uuid_nt" }
primitives = { package = "substrate-primitives", git = "https://github.com/cheme/substrate", branch = "child_uuid_nt" }
client = { package = "substrate-client", git = "https://github.com/cheme/substrate", branch = "child_uuid_nt" }
client-api = { package = "substrate-client-api", git = "https://github.com/cheme/substrate", branch = "child_uuid_nt" }
client-db = { package = "substrate-client-db", git = "https://github.com/cheme/substrate", branch = "child_uuid_nt" }
substrate-executor = { git = "https://github.com/cheme/substrate", branch = "child_uuid_nt" }
substrate-network = { git = "https://github.com/cheme/substrate", branch = "child_uuid_nt" }
consensus_common = { package = "substrate-consensus-common", git = "https://github.com/cheme/substrate", branch = "child_uuid_nt" }
grandpa = { package = "substrate-finality-grandpa", git = "https://github.com/cheme/substrate", branch = "child_uuid_nt" }
grandpa_primitives = { package = "substrate-finality-grandpa-primitives", git = "https://github.com/cheme/substrate", branch = "child_uuid_nt" }
inherents = { package = "substrate-inherents", git = "https://github.com/cheme/substrate", branch = "child_uuid_nt" }
service = { package = "substrate-service", git = "https://github.com/cheme/substrate", branch = "child_uuid_nt" }
telemetry = { package = "substrate-telemetry", git = "https://github.com/cheme/substrate", branch = "child_uuid_nt" }
transaction_pool = { package = "substrate-transaction-pool", git = "https://github.com/cheme/substrate", branch = "child_uuid_nt" }
substrate-keystore = { git = "https://github.com/cheme/substrate", branch = "child_uuid_nt" }
pallet-babe = { git = "https://github.com/cheme/substrate", default-features = false, branch = "child_uuid_nt" }
pallet-staking = { git = "https://github.com/cheme/substrate", default-features = false, branch = "child_uuid_nt" }
im-online = { package = "pallet-im-online", git = "https://github.com/cheme/substrate", default-features = false, branch = "child_uuid_nt" }
authority-discovery = { package = "substrate-authority-discovery", git = "https://github.com/cheme/substrate", branch = "child_uuid_nt" }
babe = { package = "substrate-consensus-babe", git = "https://github.com/cheme/substrate", branch = "child_uuid_nt" }
babe-primitives = { package = "substrate-consensus-babe-primitives", git = "https://github.com/cheme/substrate", default-features = false, branch = "child_uuid_nt" }
