[package]
name = "polkadot-executor"
version = "0.6.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Polkadot node implementation in Rust."
edition = "2018"

[dependencies]
substrate-executor = { git = "https://github.com/cheme/substrate", branch = "ecr-cumulus-branch" }
polkadot-runtime = { path = "../runtime" }
